version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./templates:/usr/src/app/templates
    ports:
      - "4000:80"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: simulation_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      

volumes:
  postgres_data:
